version: '3'
services:
  esc-frontend-dev:
    image: node:10-slim
    container_name: esc-frontend-dev
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command:
      sh -c 'npm install && npm run serve'
    ports:
      - "443:8080"
    networks:
      default:
        ipv4_address: 172.27.0.10
    env_file: .env

networks:
  default:
    external:
      name: esc-network
